language: java

jdk:
  - oraclejdk 1.9

#cache:
#  directories:
#    - '$HOME/.m2/repository'

#before_install:
# - chmod +x gradlew

script:
  - mvn clean package -DskipTests=true
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

branches:
  only:
    - main

notifications:
  email: false
