version: 2.1
orbs:
  orb-tools: circleci/orb-tools@11.5.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - orb-tools/publish:
          context: publishing-context
          filters:
            tags:
              only: /.*/
          orb-name: circleci/orb-tools
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
          vcs-type: << pipeline.project.type >>
      - orb-tools/continue:
          filters:
            tags:
              only: /.*/
          pipeline-number: << pipeline.number >>
          requires:
            - orb-tools/publish
          vcs-type: << pipeline.project.type >>