version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/ESTools
    environment:
      JVM_OPTS: -Xmx2g -Xmx4g
      MVN_ARGS: -Dmaven.repo.local=.repo
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=BinaryTreeNode_ESTools
      - run: java --version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn clean install package ${MVN_ARGS}
      - save_cache:
          paths:
            - .repo
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/
          destination: ESTools-jar
      - persist_to_workspace:
          root: ~/
          paths:
            - ESTools
      - run:
          command: "if mvn -q -Dexec.executable=\"echo\" -Dexec.args='${project.version}' --non-recursive exec:exec | grep -q \"SNAPSHOT\"; then mvn versions:set -DremoveSnapshot; fi;"
          name: "remove snapshot version"

  test:
    docker:
      - image: cimg/openjdk:18.0.2
    working_directory: ~/ESTools
    environment:
      JVM_OPTS: -Xmx2g -Xmx4g
      MVN_ARGS: -Dmaven.repo.local=.repo
    steps:
      - attach_workspace:
          at: ~/ESTools
      - run: |
          cd ESTools
          mvn clean test ${MVN_ARGS}
      - store_test_results:
          path: ESTools/target/surefire-reports

  deploy-site1:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - run: echo 'deploy sit1'

  deploy-site2:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - run: echo 'deploy sit2'

workflows:
  version: 2.1
  ESTools-workflow:
    jobs:
      - build:
          context: SonarCloud
          filters:
            branches:
              only: dev
      - test:
          requires:
            - build
      - approval-deploy:
          type: approval
          requires:
            - test
      - deploy-site1:
          requires:
            - approval-deploy
          filters:
            branches:
              only: main
      - deploy-site2:
          requires:
            - approval-deploy
          filters:
            branches:
              only: main

