version: '2.1'
orbs:
  my-orb: 'namespace/my-orb@dev:<<pipeline.git.revision>>'
  orb-tools: circleci/orb-tools@11.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.1
    working_directory: ~/ESTools
    environment:
      JVM_OPTS: -Xmx3200m
      MVN_ARGS: -Dmaven.repo.local=.repo
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn clean install package ${MVN_ARGS}
      - save_cache:
          paths:
            - .repo
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/
          destination: circleci-demo-jar
      - persist_to_workspace:
          root: ~/
          paths:
            - circleci-demo

  test:
    docker:
      - image: cimg/openjdk:19.0.1
    working_directory: ~/ESTools
    environment:
      JVM_OPTS: -Xmx3200m
      MVN_ARGS: -Dmaven.repo.local=.repo
    steps:
      - attach_workspace:
          at: ~/ESTools
      - run: |
          cd ESTools
          mvn clean test ${MVN_ARGS}
      - store_test_results:
          path: ESTools/target/surefire-reports

  deploy-site1:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - run: echo 'deploy sit1'

  deploy-site2:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - run: echo 'deploy sit2'

workflows:
  version: 2.1
  circleci-demo-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
      - approval-deploy:
          type: approval
          requires:
            - test
      - deploy-site1:
          requires:
            - approval-deploy
          filters:
            branches:
              only: master
      - deploy-site2:
          requires:
            - approval-deploy
          filters:
            branches:
              only: master

