# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

# trigger
on:
  push:
    branches:
      - main
      - "releases/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        architecture: x64
        cache: 'maven'
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=BinaryTreeNode_ESTools
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml')}}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir -p target/github-artifact
    - uses: actions/upload-artifact@v3
      with:
        name: ESTools artifact
        path: target/github-artifact
    - run: |
        if mvn -q -Dexec.executable=\"echo\" -Dexec.args='${project.version}' --non-recursive exec:exec | grep -q \"SNAPSHOT\"; then
            mvn versions:set -DremoveSnapshot;
        fi;

  test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          cache: 'maven'
          architecture: x64
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml')}}
          restore-keys: ${{ runner.os }}-m2
      - run: |
          mvn clean test -Dmaven.repo.local=.repo

  deploy-site1:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'deploy sit1'

  deploy-site2:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'deploy sit2'
